
services:
  # PostgreSQL database service
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # pgAdmin service for database management
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_web
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

  # FastAPI backend service
  # backend:
  #   image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
  #   container_name: fastapi_backend
  #   volumes:
  #     - ./backend:/app
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}
  #   ports:
  #     - "8000:80"
  #   depends_on:
  #     - db

  # NGINX service for serving frontend
  nginx:
    image: nginx:latest
    container_name: nginx_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
      # - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    # depends_on:
    #   - backend

volumes:
  db_data:
